services:
  webui:
    # image: "ghcr.io/TaiseiOmineS/sd-webui-forge-docker:latest"
    build: .
    volumes:
      - "./data:/app/sd-webui"
    ports:
      - "9876:9876"
    environment:
      - "ARGS=--device-id=2 --listen --enable-insecure-extension-access --xformers --skip-install"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
